# Configuration

# Dtabase
database:
  Storage: sqlite
  MySQL:
    hostname: localhost
    username: root
    database: minecraft
    port: '3306'
    password: password
    useSSL: false
  table: firepixel.db

# Spawn
spawn:
  world: world
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
  enabled_spawn_worlds:
  - world
  commands:
    hub: /server lobby
    lobby: /server lobby
    stuck: /spawn

# Language
language:
  default-language: en
  disabled_language_worlds:
  - test

# Join Messages
join-message:
  enabled: true
  default: ''
  click_command: '/viewprofile %player%'

# Report
report:
  cooldown-seconds: 60
  staff-permission: firepixel.report.staff
  appeal-link: https://firepixel.fun/appeal

# Scoreboard
scoreboard:
  enabled: true
  update_interval_ticks: 100
  scoreboard_enabled_worlds:
  - world

# Tab
tab:
  player_prefix: '%rank%'
  player_suffix: ''

# Server
server:
  id: 1
  name: Lobby